2020-07-07 17:27:59.676 [ main ] - [ INFO  ] [ c.j.platform.hotkey.dashboard.DashboardApplication : 55 ] - Starting DashboardApplication on rensailong.local with PID 77856 (/Users/sailongren/gitRes/hotkey/dashboard/target/classes started by sailongren in /Users/sailongren/gitRes/hotkey)
2020-07-07 17:27:59.679 [ main ] - [ INFO  ] [ c.j.platform.hotkey.dashboard.DashboardApplication : 655 ] - The following profiles are active: dev
2020-07-07 17:28:00.739 [ main ] - [ INFO  ] [ org.apache.coyote.http11.Http11NioProtocol : 173 ] - Initializing ProtocolHandler ["http-nio-8080"]
2020-07-07 17:28:00.740 [ main ] - [ INFO  ] [ org.apache.catalina.core.StandardService : 173 ] - Starting service [Tomcat]
2020-07-07 17:28:00.740 [ main ] - [ INFO  ] [ org.apache.catalina.core.StandardEngine : 173 ] - Starting Servlet engine: [Apache Tomcat/9.0.27]
2020-07-07 17:28:00.818 [ main ] - [ INFO  ] [ o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] : 173 ] - Initializing Spring embedded WebApplicationContext
2020-07-07 17:28:00.900 [ main ] - [ INFO  ] [ c.j.p.h.d.c.c.EtcdConfig$$EnhancerBySpringCGLIB$$7e430336 : 25 ] - etcd address : http://127.0.0.1:2380
2020-07-07 17:28:02.381 [ main ] - [ INFO  ] [ org.apache.coyote.http11.Http11NioProtocol : 173 ] - Starting ProtocolHandler ["http-nio-8080"]
2020-07-07 17:28:02.401 [ main ] - [ INFO  ] [ c.j.platform.hotkey.dashboard.DashboardApplication : 61 ] - Started DashboardApplication in 8.153 seconds (JVM running for 8.814)
2020-07-07 17:28:02.425 [ main ] - [ INFO  ] [ com.zaxxer.hikari.HikariDataSource : 110 ] - HikariPool-1 - Starting...
2020-07-07 17:28:06.959 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:28:06.961 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:28:10.516 [ main ] - [ ERROR ] [ com.zaxxer.hikari.pool.HikariPool : 595 ] - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy96.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:212)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	at com.sun.proxy.$Proxy65.delete(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:303)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:72)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:144)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
	at com.sun.proxy.$Proxy67.clear(Unknown Source)
	at com.jd.platform.hotkey.dashboard.DashboardApplication.run(DashboardApplication.java:45)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.jd.platform.hotkey.dashboard.DashboardApplication.main(DashboardApplication.java:36)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 46 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 49 common frames omitted
2020-07-07 17:29:58.226 [ main ] - [ INFO  ] [ c.j.platform.hotkey.dashboard.DashboardApplication : 55 ] - Starting DashboardApplication on rensailong.local with PID 77864 (/Users/sailongren/gitRes/hotkey/dashboard/target/classes started by sailongren in /Users/sailongren/gitRes/hotkey)
2020-07-07 17:29:58.229 [ main ] - [ INFO  ] [ c.j.platform.hotkey.dashboard.DashboardApplication : 655 ] - The following profiles are active: dev
2020-07-07 17:29:59.347 [ main ] - [ INFO  ] [ org.apache.coyote.http11.Http11NioProtocol : 173 ] - Initializing ProtocolHandler ["http-nio-8080"]
2020-07-07 17:29:59.348 [ main ] - [ INFO  ] [ org.apache.catalina.core.StandardService : 173 ] - Starting service [Tomcat]
2020-07-07 17:29:59.348 [ main ] - [ INFO  ] [ org.apache.catalina.core.StandardEngine : 173 ] - Starting Servlet engine: [Apache Tomcat/9.0.27]
2020-07-07 17:29:59.479 [ main ] - [ INFO  ] [ o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] : 173 ] - Initializing Spring embedded WebApplicationContext
2020-07-07 17:29:59.569 [ main ] - [ INFO  ] [ c.j.p.h.d.c.c.EtcdConfig$$EnhancerBySpringCGLIB$$64dc622a : 25 ] - etcd address : http://127.0.0.1:2380
2020-07-07 17:30:01.183 [ main ] - [ INFO  ] [ org.apache.coyote.http11.Http11NioProtocol : 173 ] - Starting ProtocolHandler ["http-nio-8080"]
2020-07-07 17:30:01.205 [ main ] - [ INFO  ] [ c.j.platform.hotkey.dashboard.DashboardApplication : 61 ] - Started DashboardApplication in 8.511 seconds (JVM running for 9.003)
2020-07-07 17:30:01.227 [ main ] - [ INFO  ] [ com.zaxxer.hikari.HikariDataSource : 110 ] - HikariPool-1 - Starting...
2020-07-07 17:30:01.422 [ main ] - [ INFO  ] [ com.zaxxer.hikari.HikariDataSource : 123 ] - HikariPool-1 - Start completed.
2020-07-07 17:30:01.476 [ main ] - [ INFO  ] [ c.j.p.h.d.DashboardApplication$$EnhancerBySpringCGLIB$$83ae2acb : 46 ] - clear db timely hotKey, effect row : {}
2020-07-07 17:30:05.733 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:05.734 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:10.766 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:10.767 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:15.845 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:15.846 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:20.923 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:20.924 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:25.956 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:25.957 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:31.040 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:31.041 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:36.053 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:36.054 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:41.061 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:41.061 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:46.151 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:46.151 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:48.268 [ http-nio-8080-exec-1 ] - [ INFO  ] [ o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] : 173 ] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-07-07 17:30:51.230 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:51.230 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:30:56.260 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:30:56.260 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:01.278 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:01.279 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:06.356 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:06.356 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:11.365 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:11.366 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:16.383 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:16.383 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:21.435 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:21.437 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:26.461 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:26.462 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:31.541 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:31.543 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:36.558 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:36.558 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:41.573 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:41.573 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:46.641 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:46.641 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:51.660 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:51.661 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:31:56.695 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:31:56.695 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:01.702 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:01.703 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:06.760 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:06.760 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:11.835 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:11.836 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:16.861 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:16.861 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:21.888 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:21.889 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:26.923 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:26.924 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:31.947 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:31.948 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:37.011 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:37.012 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:42.058 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:42.059 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:47.142 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:47.142 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:52.223 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:52.223 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:32:57.263 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:32:57.263 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:02.289 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:02.290 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:07.362 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:07.363 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:12.382 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:12.383 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:17.408 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:17.408 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:22.461 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:22.461 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:27.474 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:27.475 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:32.496 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:32.496 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:37.508 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:37.509 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:42.527 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:42.528 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:47.561 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:47.561 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:52.641 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:52.642 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:33:57.663 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:33:57.663 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:02.675 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:02.675 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:07.738 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:07.739 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:12.764 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:12.764 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:17.773 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:17.774 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:22.812 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:22.812 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:27.865 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:27.865 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:32.879 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:32.880 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:37.901 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:37.901 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:42.965 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:42.965 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:47.973 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:47.973 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:53.053 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:53.055 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:34:58.087 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:34:58.087 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:35:03.155 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:35:03.155 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:35:08.223 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:35:08.223 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:35:13.265 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:35:13.266 [ etcd-event-pool-1 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:35:18.292 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.GrpcClient : 637 ] - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
2020-07-07 17:35:18.292 [ etcd-event-pool-4 ] - [ INFO  ] [ com.ibm.etcd.client.watch.EtcdWatchClient : 415 ] - onReplaced called for watch request stream
2020-07-07 17:35:19.461 [ SpringContextShutdownHook ] - [ INFO  ] [ com.zaxxer.hikari.HikariDataSource : 350 ] - HikariPool-1 - Shutdown initiated...
2020-07-07 17:35:19.479 [ SpringContextShutdownHook ] - [ INFO  ] [ com.zaxxer.hikari.HikariDataSource : 352 ] - HikariPool-1 - Shutdown completed.
